//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pProduct
    {
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Abstract { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }
        public System.DateTime DateAdded { get; set; }
    }
}
